---
title: "PBARC QLB colony"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
date: "`r Sys.Date()`"
---


```{r setup, include = F} 

library(tidyverse)
library(plyr)
library(broom)
library(dplyr)
library(ggplot2)
library(readxl)
library(flexdashboard)
library(wesanderson)
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
library(Ckmeans.1d.dp)

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sem = sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}

pal1 <- wes_palette("Darjeeling1", 5, type = "continuous")
pal2 <- wes_palette("FantasticFox1", 5, type = "continuous")
pal3 <- wes_palette("Cavalcanti1", 5, type = "continuous")


```

```{r Read in file}
colony_lifestages_df <- readxl::read_xlsx("qlb_colony_spreadsheet.xlsx", col_names=T, sheet="lifestages") %>% 
  gather(key = "Life stage", value = "Count", -Date) %>% 
  mutate(`Life stage` = fct_relevel(`Life stage`, "Larva", "Pupa", "Adult female", "Adult male", "Adult mating")) 

headcapsule_widths <- readxl::read_xlsx("qlb_colony_spreadsheet.xlsx", col_names=T, sheet="headcapsule", na = "--") %>% 
  gather(key = "Head capsule measurement collection", value = "Width", 7:20) %>% 
  drop_na(Width) %>% 
  dplyr::select("Name", "Substrate", "Head capsule measurement collection", "Width") %>% 
  mutate(Name_collection = paste(Name, "_", `Head capsule measurement collection`)) %>% 
  dplyr::select(Name_collection, Width) %>% 
  column_to_rownames(var = "Name_collection")

# View(colony_lifestages_df)
```

### QLB colony individuals by life stage

```{r plot stackedbar}
ggplot(colony_lifestages_df, aes(fill=`Life stage`, y=Count, x=Date)) + 
    geom_bar(position="stack", stat="identity") +
    theme_bw() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),) +
    xlab("") +
    scale_y_continuous(labels = scales::number_format(accuracy = 1)) + 
    scale_fill_manual(values=pal3)

```

```{r plot headcapsule widths}
result <- Ckmeans.1d.dp(headcapsule_widths$Width, 14)
# plot(result)
# result

hc_density_hist <- ggplot(headcapsule_widths, aes(Width)) +
  geom_histogram(binwidth = 0.2) +
  geom_density(adjust = 1/5, aes(y=0.2 * ..count..)) +
  theme_bw()

hc_density_hist

# ggsave(hc_density_hist, file = "density_hist.png", device = "png", width = 6, height = 4, units = "in")
```
